controller_manager:
    ros__parameters:
        update_rate: 500

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        omni_controller:
            type: omni_controller/OmniController
        
        imu_sensor:
            type: imu_sensor_broadcaster/IMUSensorBroadcaster

imu_sensor:
    ros__parameters:
        frame_id: imu_link
        sensor_name: Pi3Hat

omni_controller:
    ros__parameters:
        wheel_joints:
            LF: LF_WHEEL_JNT
            LH: LH_WHEEL_JNT
            RF: RF_WHEEL_JNT
            RH: RH_WHEEL_JNT

        # leg_joints: #omitted — defaults to empty. Do NOT use "[]" (ROS 2 can't infer the type)
        #     - ... 

        distributor_names:
            - Distributor_R
            - Distributor_L

        second_encoder_joints:
            - LF_WHEEL_JNT
            - LH_WHEEL_JNT
            - RF_WHEEL_JNT
            - RH_WHEEL_JNT

        feet_type: mecanum
        wheel_rad: 0.05
        driveshaft_x: 0.235
        driveshaft_y: 0.188
        mecanum_angle: 135.0

        input_frequency: 100
        BestEffort_QOS: true

        sim: false
        pub_odom: false
        pub_performance: true
